export const noti = [
        {
            id: 1,
            title: 'Bạn có 1 người theo dõi mới!',
            userName: 'Nguyễn Minh Anh',
            content: 'vừa theo dõi bạn. Hãy cập nhật hồ sơ để tăng số lượng ứng tuyển!',
            timestamp: '2023-10-01T12:00:00Z',
        },
        {
            id: 2,
            title: 'Ứng viên mới cho vị trí Kỹ sư phần mềm',
            userName: 'Nguyễn Minh Anh',
            content: 'đã nộp đơn ứng tuyển cho vị trí Kỹ sư phần mềm. Hãy xem xét hồ sơ của họ!',
            timestamp: '2023-10-02T14:30:00Z',
        },
        {
            id: 3,
            title: 'Bạn có một tin nhắn mới',
            userName: 'Nguyễn Thị B',
            content: 'đã gửi cho bạn một tin nhắn. Hãy kiểm tra hộp thư của bạn để xem chi tiết.',
            timestamp: '2023-10-03T09:15:00Z',
        },
        {
            id: 4,
            title: 'Thông báo từ hệ thống',
            userName: 'Hệ thống',
            content: 'Đã cập nhật chính sách bảo mật. Vui lòng xem lại để đảm bảo bạn hiểu rõ.',
            timestamp: '2023-10-04T16:45:00Z',
        },
        {
            id: 5,
            title: 'Bạn có một lời mời kết nối mới',
            userName: 'Trần Văn C',
            content: 'đã gửi lời mời kết nối với bạn. Hãy chấp nhận hoặc từ chối lời mời này.',
            timestamp: '2023-10-05T11:20:00Z',
        },
        {
            id: 6,
            title: 'Thông báo từ hệ thống',
            userName: 'Hệ thống',
            content: 'Đã cập nhật chính sách bảo mật. Vui lòng xem lại để đảm bảo bạn hiểu rõ.',
            timestamp: '2023-10-06T08:00:00Z',
        },
        {
            id: 7,
            title: 'Bạn có một lời mời kết nối mới',
            userName: 'Trần Văn D',
            content: 'đã gửi lời mời kết nối với bạn. Hãy chấp nhận hoặc từ chối lời mời này.',
            timestamp: '2023-10-07T10:30:00Z',
        },
        {
            id: 8,
            title: 'Thông báo từ hệ thống',
            userName: 'Hệ thống',
            content: 'Đã cập nhật chính sách bảo mật. Vui lòng xem lại để đảm bảo bạn hiểu rõ.',
            timestamp: '2023-10-08T15:00:00Z',
        },
        {
            id: 9,
            title: 'Bạn có một lời mời kết nối mới',
            userName: 'Nguyễn Văn E',
            content: 'đã gửi lời mời kết nối với bạn. Hãy chấp nhận hoặc từ chối lời mời này.',
            timestamp: '2023-10-09T13:45:00Z',
        },
        {
            id: 10,
            title: 'Thông báo từ hệ thống',
            userName: 'Hệ thống',
            content: 'Đã cập nhật chính sách bảo mật. Vui lòng xem lại để đảm bảo bạn hiểu rõ.',
            timestamp: '2023-10-10T17:30:00Z',
        },
        {
            id: 11,
            title: 'Bạn có một lời mời kết nối mới',
            userName: 'Nguyễn Văn F',
            content: 'đã gửi lời mời kết nối với bạn. Hãy chấp nhận hoặc từ chối lời mời này.',
            timestamp: '2023-10-11T12:00:00Z',
        },
        {
            id: 12,
            title: 'Thông báo từ hệ thống',
            userName: 'Hệ thống',
            content: 'Đã cập nhật chính sách bảo mật. Vui lòng xem lại để đảm bảo bạn hiểu rõ.',
            timestamp: '2023-10-12T14:30:00Z',
        },
        {
            id: 13,
            title: 'Bạn có một lời mời kết nối mới',
            userName: 'Nguyễn Văn G',
            content: 'đã gửi lời mời kết nối với bạn. Hãy chấp nhận hoặc từ chối lời mời này.',
            timestamp: '2023-10-13T09:15:00Z',
        },
        {
            id: 14,
            title: 'Thông báo từ hệ thống',
            userName: 'Hệ thống',
            content: 'Đã cập nhật chính sách bảo mật. Vui lòng xem lại để đảm bảo bạn hiểu rõ.',
            timestamp: '2023-10-14T16:45:00Z',
        },
        {
            id: 15,
            title: 'Bạn có một lời mời kết nối mới',
            userName: 'Nguyễn Văn H',
            content: 'đã gửi lời mời kết nối với bạn. Hãy chấp nhận hoặc từ chối lời mời này.',
            timestamp: '2023-10-15T11:20:00Z',
        },
    ];