import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import Logo from "../../public/Gigbuds Logo.png";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gigbuds",
  icons: {
    icon: Logo.src,
    shortcut: Logo.src,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex w-screen h-screen"> 
          <div className="lg:w-[20%] md:w-[40%] sm:w-[40%] w-[40%]">
            <Sidebar /> 
          </div>
          <main className="lg:w-[80%] md:w[60%] sm:w-[60%] w-[60%] bg-amber-200"> {/* Added a main tag to wrap children */}
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
