import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Sidebar from "@/components/Sidebar/Sidebar"; // No longer needed here
import Logo from "../../public/Gigbuds Logo.png";
import LayoutClientShell from "./LayoutClientShell";
// import { usePathname } from "next/navigation"; // No longer needed here


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gigbuds",
  icons: {
    icon: Logo.src,
    shortcut: Logo.src,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname(); // Logic moved to LayoutClientShell
  // const isLoginPage = pathname === "/Login"; // Logic moved to LayoutClientShell

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
        <LayoutClientShell>{children}</LayoutClientShell>
      </body>
    </html>
  );
}
