import "@ant-design/v5-patch-for-react-19";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "../../public/Gigbuds Logo.png";
import LayoutClientShell from "./LayoutClientShell";
import StoreProvider from "@/components/providers/StoreProvider";
import { LoadingProvider } from "@/contexts/LoadingContext";
import { SignalRProvider } from "@/contexts/SignalRProvider";
import { MessagingSignalRProvider } from "@/contexts/MessagingSignalRProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gigbuds",
  icons: {
    icon: Logo.src,
    shortcut: Logo.src,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <StoreProvider>
            <MessagingSignalRProvider>
              <SignalRProvider>
                <LoadingProvider>
                  <LayoutClientShell>{children}</LayoutClientShell>
                </LoadingProvider>
              </SignalRProvider>
            </MessagingSignalRProvider>
          </StoreProvider>
      </body>
    </html>
  );
}
